#!/bin/bash
set -euo pipefail

killit() {
  local proc="$(ps -ahxo 'comm' | sort | uniq \
                | rofi -i -dmenu -p 'pkill')"
  if [[ -z "$proc" ]]; then
    return 1
  fi
  pkill "$proc"
}

main() {
  if [[ "${1:-}" = --loop ]]; then
    while killit; do
      :
    done
  else
    killit
  fi
}

main "$@"

# vim: ft=sh
